# Generated by Django 4.0.3 on 2022-03-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_genre_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='URL',
            field=models.URLField(blank=True),
        ),
    ]
